name: social_graphs
dependencies:
  - python=3.7
  - ipykernel
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - setuptools
  - networkx = 2.5
  - pip
  - pip:
      - "--editable ."
      - black
      - nb_black
